### ISSUE TITLE
data tiles rendering as blue

### ISSUE THREAD

**Issue by derekeder** [datamade/lascaux#9]
Data layer is rendering with a blue hue in the final PDF:

input
![screen shot 2015-04-22 at 3 23 08 pm](https://cloud.githubusercontent.com/assets/919583/7284466/8025c382-e903-11e4-83a8-48cd65ad26a8.png)

output
![screen shot 2015-04-22 at 3 24 00 pm](https://cloud.githubusercontent.com/assets/919583/7284481/9f2d3abc-e903-11e4-8dde-bbe4b11aa8e9.png)

**Comment by fgregg** [comment]
Cool!
